export interface Emotion {
  id: string;
  name: string;
  color: string;
  lightColor: string;
  darkColor: string;
  description: string;
  triggers: string[];
  relatedEmotions: string[];
  recommendations: string[];
  layer: number;
  angle: number;
  parent?: string;
}

export const coreEmotions: Emotion[] = [
  // Joy sector (0-45°)
  {
    id: 'joy',
    name: 'Joy',
    color: '#FBBF24',
    lightColor: '#FEF3C7',
    darkColor: '#92400E',
    description: 'A feeling of great pleasure and happiness.',
    triggers: ['Achievement', 'Connection', 'Gratitude', 'Success'],
    relatedEmotions: ['Happiness', 'Contentment', 'Excitement', 'Pride'],
    recommendations: ['Savor the moment', 'Share with others', 'Practice gratitude', 'Journal your joy'],
    layer: 0,
    angle: 22.5,
  },
  {
    id: 'ecstasy',
    name: 'Ecstasy',
    color: '#F59E0B',
    lightColor: '#FEF3C7',
    darkColor: '#78350F',
    description: 'An overwhelming feeling of great happiness.',
    triggers: ['Major achievement', 'Deep love', 'Spiritual experience'],
    relatedEmotions: ['Joy', 'Euphoria', 'Bliss'],
    recommendations: ['Ground yourself', 'Breathe deeply', 'Stay present'],
    layer: 1,
    angle: 10,
    parent: 'joy',
  },
  {
    id: 'pride',
    name: 'Pride',
    color: '#D97706',
    lightColor: '#FEF3C7',
    darkColor: '#7C2D12',
    description: 'A feeling of deep pleasure from achievements.',
    triggers: ['Accomplishment', 'Recognition', 'Personal growth'],
    relatedEmotions: ['Joy', 'Confidence', 'Satisfaction'],
    recommendations: ['Celebrate mindfully', 'Share with loved ones', 'Reflect on the journey'],
    layer: 1,
    angle: 35,
    parent: 'joy',
  },

  // Trust sector (45-90°)
  {
    id: 'trust',
    name: 'Trust',
    color: '#34D399',
    lightColor: '#D1FAE5',
    darkColor: '#065F46',
    description: 'A firm belief in reliability or truth.',
    triggers: ['Consistent behavior', 'Honesty', 'Vulnerability', 'Support'],
    relatedEmotions: ['Safety', 'Comfort', 'Acceptance', 'Love'],
    recommendations: ['Build boundaries', 'Communicate openly', 'Practice self-trust'],
    layer: 0,
    angle: 67.5,
  },
  {
    id: 'admiration',
    name: 'Admiration',
    color: '#10B981',
    lightColor: '#D1FAE5',
    darkColor: '#047857',
    description: 'Respect and warm approval for someone or something.',
    triggers: ['Witnessing excellence', 'Acts of kindness', 'Bravery'],
    relatedEmotions: ['Trust', 'Respect', 'Inspiration'],
    recommendations: ['Express appreciation', 'Learn from them', 'Find inspiration'],
    layer: 1,
    angle: 55,
    parent: 'trust',
  },
  {
    id: 'acceptance',
    name: 'Acceptance',
    color: '#059669',
    lightColor: '#D1FAE5',
    darkColor: '#064E3B',
    description: 'The action of consenting to receive or undertake.',
    triggers: ['Understanding', 'Forgiveness', 'Self-awareness'],
    relatedEmotions: ['Trust', 'Peace', 'Contentment'],
    recommendations: ['Practice self-compassion', 'Let go of judgment', 'Embrace imperfection'],
    layer: 1,
    angle: 80,
    parent: 'trust',
  },

  // Fear sector (90-135°)
  {
    id: 'fear',
    name: 'Fear',
    color: '#8B5CF6',
    lightColor: '#EDE9FE',
    darkColor: '#4C1D95',
    description: 'An unpleasant emotion caused by danger or threat.',
    triggers: ['Uncertainty', 'Change', 'Past trauma', 'Unknown situations'],
    relatedEmotions: ['Anxiety', 'Worry', 'Nervousness', 'Apprehension'],
    recommendations: ['Ground yourself', 'Breathe deeply', 'Challenge thoughts', 'Seek safety'],
    layer: 0,
    angle: 112.5,
  },
  {
    id: 'anxiety',
    name: 'Anxiety',
    color: '#7C3AED',
    lightColor: '#EDE9FE',
    darkColor: '#5B21B6',
    description: 'A feeling of worry, nervousness, or unease.',
    triggers: ['Future uncertainty', 'Social situations', 'Health concerns', 'Work stress'],
    relatedEmotions: ['Fear', 'Worry', 'Nervousness', 'Tension'],
    recommendations: ['Grounding exercises', 'Box breathing', 'Challenge anxious thoughts', 'Limit caffeine'],
    layer: 1,
    angle: 100,
    parent: 'fear',
  },
  {
    id: 'apprehension',
    name: 'Apprehension',
    color: '#6D28D9',
    lightColor: '#EDE9FE',
    darkColor: '#4C1D95',
    description: 'Anxiety or fear that something unpleasant will happen.',
    triggers: ['Upcoming events', 'Uncertain outcomes', 'Anticipation'],
    relatedEmotions: ['Fear', 'Worry', 'Dread'],
    recommendations: ['Prepare mindfully', 'Focus on present', 'Practice acceptance'],
    layer: 1,
    angle: 125,
    parent: 'fear',
  },

  // Surprise sector (135-180°)
  {
    id: 'surprise',
    name: 'Surprise',
    color: '#F472B6',
    lightColor: '#FCE7F3',
    darkColor: '#9D174D',
    description: 'An unexpected or astonishing event or fact.',
    triggers: ['Unexpected news', 'Sudden changes', 'New information', 'Disruption'],
    relatedEmotions: ['Shock', 'Amazement', 'Wonder', 'Disbelief'],
    recommendations: ['Pause and breathe', 'Process gradually', 'Stay grounded', 'Seek clarity'],
    layer: 0,
    angle: 157.5,
  },
  {
    id: 'amazement',
    name: 'Amazement',
    color: '#EC4899',
    lightColor: '#FCE7F3',
    darkColor: '#831843',
    description: 'A feeling of great surprise or wonder.',
    triggers: ['Extraordinary events', 'Beauty', 'Talent', 'Nature'],
    relatedEmotions: ['Surprise', 'Awe', 'Wonder'],
    recommendations: ['Stay present', 'Express gratitude', 'Share the experience'],
    layer: 1,
    angle: 145,
    parent: 'surprise',
  },
  {
    id: 'shock',
    name: 'Shock',
    color: '#DB2777',
    lightColor: '#FCE7F3',
    darkColor: '#831843',
    description: 'A sudden upsetting or surprising event.',
    triggers: ['Unexpected news', 'Trauma', 'Sudden loss', 'Accident'],
    relatedEmotions: ['Surprise', 'Fear', 'Disbelief'],
    recommendations: ['Ground yourself', 'Seek support', 'Allow processing time', 'Breathe'],
    layer: 1,
    angle: 170,
    parent: 'surprise',
  },

  // Sadness sector (180-225°)
  {
    id: 'sadness',
    name: 'Sadness',
    color: '#60A5FA',
    lightColor: '#DBEAFE',
    darkColor: '#1E40AF',
    description: 'A feeling of sorrow or unhappiness.',
    triggers: ['Loss', 'Disappointment', 'Rejection', 'Loneliness'],
    relatedEmotions: ['Grief', 'Melancholy', 'Sorrow', 'Despair'],
    recommendations: ['Allow yourself to feel', 'Reach out to others', 'Practice self-care', 'Journal your feelings'],
    layer: 0,
    angle: 202.5,
  },
  {
    id: 'grief',
    name: 'Grief',
    color: '#3B82F6',
    lightColor: '#DBEAFE',
    darkColor: '#1E3A8A',
    description: 'Deep sorrow, especially from loss.',
    triggers: ['Death of loved one', 'Major life change', 'End of relationship'],
    relatedEmotions: ['Sadness', 'Anguish', 'Longing'],
    recommendations: ['Allow grieving process', 'Seek support', 'Honor the loss', 'Practice patience'],
    layer: 1,
    angle: 190,
    parent: 'sadness',
  },
  {
    id: 'melancholy',
    name: 'Melancholy',
    color: '#2563EB',
    lightColor: '#DBEAFE',
    darkColor: '#1E3A8A',
    description: 'A feeling of pensive sadness, often with no cause.',
    triggers: ['Reflection', 'Memories', 'Seasonal changes', 'Fatigue'],
    relatedEmotions: ['Sadness', 'Nostalgia', 'Longing'],
    recommendations: ['Create something', 'Connect with nature', 'Listen to music', 'Express through art'],
    layer: 1,
    angle: 215,
    parent: 'sadness',
  },

  // Disgust sector (225-270°)
  {
    id: 'disgust',
    name: 'Disgust',
    color: '#A3E635',
    lightColor: '#ECFCCB',
    darkColor: '#365314',
    description: 'A feeling of revulsion or strong disapproval.',
    triggers: ['Unpleasant experiences', 'Moral violations', 'Physical repulsion', 'Betrayal'],
    relatedEmotions: ['Revulsion', 'Contempt', 'Aversion', 'Shame'],
    recommendations: ['Identify the source', 'Set boundaries', 'Practice acceptance', 'Seek understanding'],
    layer: 0,
    angle: 247.5,
  },
  {
    id: 'contempt',
    name: 'Contempt',
    color: '#84CC16',
    lightColor: '#ECFCCB',
    darkColor: '#3F6212',
    description: 'The feeling that someone is beneath consideration.',
    triggers: ['Perceived inferiority', 'Betrayal of values', 'Disrespect'],
    relatedEmotions: ['Disgust', 'Anger', 'Disappointment'],
    recommendations: ['Examine your judgments', 'Practice empathy', 'Set healthy boundaries'],
    layer: 1,
    angle: 235,
    parent: 'disgust',
  },
  {
    id: 'shame',
    name: 'Shame',
    color: '#65A30D',
    lightColor: '#ECFCCB',
    darkColor: '#365314',
    description: 'A painful feeling of humiliation or distress.',
    triggers: ['Mistakes', 'Social judgment', 'Failure', 'Trauma'],
    relatedEmotions: ['Guilt', 'Embarrassment', 'Regret'],
    recommendations: ['Practice self-compassion', 'Challenge negative thoughts', 'Talk to someone you trust'],
    layer: 1,
    angle: 260,
    parent: 'disgust',
  },

  // Anger sector (270-315°)
  {
    id: 'anger',
    name: 'Anger',
    color: '#F87171',
    lightColor: '#FEE2E2',
    darkColor: '#991B1B',
    description: 'A strong feeling of annoyance or hostility.',
    triggers: ['Injustice', 'Frustration', 'Betrayal', 'Boundary violation'],
    relatedEmotions: ['Frustration', 'Rage', 'Irritation', 'Resentment'],
    recommendations: ['Box breathing', 'Physical activity', 'Journal your feelings', 'Take a walk'],
    layer: 0,
    angle: 292.5,
  },
  {
    id: 'rage',
    name: 'Rage',
    color: '#EF4444',
    lightColor: '#FEE2E2',
    darkColor: '#7F1D1D',
    description: 'Violent, uncontrollable anger.',
    triggers: ['Extreme injustice', 'Betrayal', 'Accumulated frustration'],
    relatedEmotions: ['Anger', 'Fury', 'Wrath'],
    recommendations: ['Remove yourself from situation', 'Deep breathing', 'Seek professional support'],
    layer: 1,
    angle: 280,
    parent: 'anger',
  },
  {
    id: 'frustration',
    name: 'Frustration',
    color: '#DC2626',
    lightColor: '#FEE2E2',
    darkColor: '#7F1D1D',
    description: 'The feeling of being upset or annoyed.',
    triggers: ['Blocked goals', 'Unmet expectations', 'Repeated failures'],
    relatedEmotions: ['Anger', 'Irritation', 'Disappointment'],
    recommendations: ['Take a break', 'Identify the obstacle', 'Practice patience', 'Reframe the situation'],
    layer: 1,
    angle: 305,
    parent: 'anger',
  },

  // Anticipation sector (315-360°)
  {
    id: 'anticipation',
    name: 'Anticipation',
    color: '#FB923C',
    lightColor: '#FFEDD5',
    darkColor: '#9A3412',
    description: 'Excited expectation or prediction.',
    triggers: ['Future events', 'Planning', 'Hope', 'Desire'],
    relatedEmotions: ['Excitement', 'Hope', 'Eagerness', 'Expectation'],
    recommendations: ['Stay present', 'Prepare mindfully', 'Manage expectations', 'Enjoy the journey'],
    layer: 0,
    angle: 337.5,
  },
  {
    id: 'excitement',
    name: 'Excitement',
    color: '#F97316',
    lightColor: '#FFEDD5',
    darkColor: '#9A3412',
    description: 'A feeling of great enthusiasm and eagerness.',
    triggers: ['Positive events', 'New experiences', 'Achievements', 'Adventure'],
    relatedEmotions: ['Anticipation', 'Joy', 'Enthusiasm'],
    recommendations: ['Channel energy positively', 'Stay grounded', 'Share with others'],
    layer: 1,
    angle: 325,
    parent: 'anticipation',
  },
  {
    id: 'hope',
    name: 'Hope',
    color: '#EA580C',
    lightColor: '#FFEDD5',
    darkColor: '#7C2D12',
    description: 'A feeling of expectation and desire for good things.',
    triggers: ['Possibility', 'Faith', 'Encouragement', 'New beginnings'],
    relatedEmotions: ['Anticipation', 'Optimism', 'Faith'],
    recommendations: ['Nurture your hope', 'Take positive action', 'Surround yourself with support'],
    layer: 1,
    angle: 350,
    parent: 'anticipation',
  },
];

export const getEmotionById = (id: string): Emotion | undefined => {
  return coreEmotions.find(e => e.id === id);
};

export const getEmotionsByLayer = (layer: number): Emotion[] => {
  return coreEmotions.filter(e => e.layer === layer);
};

export const getParentEmotions = (): Emotion[] => {
  return coreEmotions.filter(e => e.layer === 0);
};
